# Generated by Django 4.2.7 on 2025-10-13 07:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import teams.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre del Equipo')),
                ('team_photo', models.ImageField(blank=True, null=True, upload_to=teams.models.team_photo_path, verbose_name='Foto del Equipo')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='Victorias')),
                ('losses', models.PositiveIntegerField(default=0, verbose_name='Derrotas')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Puntos Totales')),
                ('bracket_status', models.CharField(choices=[('winners', 'Winners Bracket'), ('losers', 'Losers Bracket'), ('eliminated', 'Eliminado'), ('champion', 'Campeón')], default='winners', max_length=20, verbose_name='Estado en Bracket')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-points', '-wins', 'name'],
                'unique_together': {('tournament', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre del Jugador')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=teams.models.player_photo_path, verbose_name='Foto del Jugador')),
                ('is_captain', models.BooleanField(default=False, verbose_name='Es Capitán')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'unique_together': {('team', 'name')},
            },
        ),
    ]
