# Generated by Django 4.2.7 on 2025-11-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name_changed',
            field=models.BooleanField(default=False, verbose_name='Nombre ya fue cambiado'),
        ),
    ]
