# Generated by Django 4.2.7 on 2025-10-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Torneo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('tournament_type', models.CharField(choices=[('single', 'Eliminación Simple'), ('double', 'Eliminación Doble')], default='single', max_length=10, verbose_name='Tipo de Torneo')),
                ('status', models.CharField(choices=[('setup', 'Configuración'), ('registration', 'Registro Abierto'), ('active', 'En Progreso'), ('completed', 'Finalizado')], default='setup', max_length=20, verbose_name='Estado')),
                ('max_teams', models.PositiveIntegerField(default=16, verbose_name='Máximo de Equipos')),
                ('points_per_win', models.PositiveIntegerField(default=3, verbose_name='Puntos por Victoria')),
                ('points_per_participation', models.PositiveIntegerField(default=1, verbose_name='Puntos por Participación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
                'ordering': ['-created_at'],
            },
        ),
    ]
