# Generated by Django 4.2.7 on 2025-10-13 07:14

from django.db import migrations, models
import django.db.models.deletion
import games.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Juego')),
                ('emoji', models.CharField(blank=True, max_length=10, verbose_name='Emoji Identificador')),
                ('image', models.ImageField(blank=True, null=True, upload_to=games.models.game_image_path, verbose_name='Imagen del Juego')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_predefined', models.BooleanField(default=False, verbose_name='Juego Predefinido')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
                'ordering': ['is_predefined', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TournamentGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=True, verbose_name='Seleccionado para el Torneo')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_games', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Juego del Torneo',
                'verbose_name_plural': 'Juegos del Torneo',
                'unique_together': {('tournament', 'game')},
            },
        ),
    ]
